server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gerrysousa/spring-cloud-service-registry-config.git
          search-paths: microservices-repo
          default-label: main